# airflow/dags/dag_2_mysql_to_bigquery.py
from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.google.cloud.transfers.mysql_to_gcs import MySQLToGCSOperator
from airflow.providers.google.cloud.transfers.gcs_to_bigquery import GCSToBigQueryOperator
from airflow.operators.trigger_dagrun import TriggerDagRunOperator
from airflow.utils.task_group import TaskGroup

TABLES_TO_MIGRATE = ['rental', 'payment', 'customer', 'film', 'actor', 'film_actor', 'inventory']

GCS_BUCKET = 'sakila-landing-zone-quang-2026'
BQ_RAW_DATASET = 'sakila_raw'

default_args = {
    'owner': 'senior_mentor',
    'depends_on_past': False,                           # Set to False for trigger-driven execution
    'retries': 2,
    'retry_delay': timedelta(seconds=15),
    'retry_exponential_backoff': True,
    'max_retry_delay': timedelta(minutes=2),
}

with DAG(
    dag_id='dag_2_mysql_to_bigquery',
    default_args=default_args,
    description='Daily incremental extraction to GCS Parquet and load to column-partitioned BigQuery',
    schedule=None,                                     # TRIGGER-ONLY: Prevents duplicate scheduled runs
    start_date=datetime(2026, 1, 1),
    max_active_runs=3,                                 # HARD REQUIREMENT: Concurrency capped at 3
    catchup=False,                                     # Set to False for trigger-driven execution
    tags=['production_ingestion', 'parquet', 'daily_delta']
) as dag:

    with TaskGroup(group_id='incremental_ingestion_group') as ingestion_group:
        for table in TABLES_TO_MIGRATE:
            
            # Using ds (YYYY-MM-DD) and ds_nodash (YYYYMMDD) macros for deterministic pathing
            gcs_date_partition = "date={{ ds }}"
            bq_partition_decorator = "{{ ds_nodash }}"

            # Task A: Extract Daily Delta using macros to build an explicit 24-hour window
            extract_to_gcs = MySQLToGCSOperator(
                task_id=f'extract_{table}_to_gcs',
                mysql_conn_id='mysql_local',
                sql=f"""
                    SELECT * FROM {table} 
                    WHERE last_update >= '{{{{ ds }}}} 00:00:00' 
                      AND last_update < '{{{{ macros.ds_add(ds, 1) }}}} 00:00:00'
                """,
                bucket=GCS_BUCKET,
                # Explain "{table}_{{}}.parquet": The "{}" is a placeholder for the chunk number, 
                # which is automatically generated by the operator when splitting large datasets into multiple files.
                filename=f'raw/sakila/{table}/{gcs_date_partition}/{table}_{{}}.parquet',
                export_format='parquet',
                approx_max_file_size_bytes=134217728,  # 128 MB Chunk Size
                gcp_conn_id='google_cloud_default'
            )

            # Task B: Load Parquet chunks into Column-Partitioned BigQuery Table
            load_to_bq = GCSToBigQueryOperator(
                task_id=f'load_{table}_to_bigquery',
                bucket=GCS_BUCKET,
                source_objects=[f'raw/sakila/{table}/{gcs_date_partition}/*.parquet'],
                destination_project_dataset_table=f'{BQ_RAW_DATASET}.raw_{table}',
                source_format='PARQUET',
                write_disposition='WRITE_APPEND',       # Appends daily delta into last_update column partition
                autodetect=True,
                time_partitioning={
                    "type": "DAY",
                    "field": "last_update"
                },
                gcp_conn_id='google_cloud_default'
            )

            extract_to_gcs >> load_to_bq

    # Task C: Cascade execution to downstream dbt incremental transformations
    trigger_dbt_transformation = TriggerDagRunOperator(
        task_id='invoke_dag_3_dbt_transformation',
        trigger_dag_id='dag_3_dbt_transformation',
        # Explain the below parameters:
        # - wait_for_completion=False: The current DAG will not wait for the triggered DAG to finish before marking this task as complete. This allows for asynchronous execution.
        # - reset_dag_run=True: If the triggered DAG has already run for the same execution date, it will reset and rerun it. This is useful for reprocessing data if needed.
        # - allowed_states=['success']: The current DAG will only consider the triggered DAG run successful if it reaches a 'success' state. 
        #       If the triggered DAG fails or is in any other state, it will not be considered successful for the current DAG's execution.
        wait_for_completion=False,
        reset_dag_run=True,
        allowed_states=['success']
    )

    ingestion_group >> trigger_dbt_transformation